collections:
  research:
    output: true
  blog:
    output: true

defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "research"
    values:
      layout: "research"
  - scope:
      path: ""
    values:
      layout: "default"


title: Epoch
theme: minima

# Blog posts URLs
collections:
  blog:
    output: true
    permalink: /:collection/:title
  research:
    output: true

url: https://epochai.org
baseurl: /
domain: epochai.org

# Top level pages
include:
  - _pages

sass:
  sass_dir: assets/css
  load_paths:
    - _sass
    - assets/bundles/compute-calculator

exclude:
  - CNAME
  - firebase-dev.json
  - firebase.json
  - README.md
  - assets/images/README.md
  - coming_soon

bootstrap:
  version: "4.6.1"
  integrity:
    css: "sha256-DF7Zhf293AJxJNTmh5zhoYYIMs2oXitRfBjY+9L//AY="
    js: "sha256-SyTu6CwrfOhaznYZPoolVw2rxoY7lKYKQvqbtqN93HI="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
mathjax:
  version: "3.2.0"
mdb:
  version: "4.20.0"
  integrity:
    css: "sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw="
    js: "sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA="
popper:
  version: "2.11.2"
  integrity: "sha256-l/1pMF/+J4TThfgARS6KwWrk/egwuVvhRzfLAMQ6Ds4="
tippy:
  version: "6.2.6"

plugins:
  - jekyll-toc

# To make GitHub Pages work with our domain
#include: [CNAME]
