collections:
  research:
    output: true
  blog:
    output: true

defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "research"
    values:
      layout: "article"
  - scope:
      path: ""
    values:
      layout: "default"


title: Epoch
theme: minima

url: epochai.org
baseurl: /

exclude: [README.md]

# To make GitHub Pages work with our domain
include: [CNAME]

