name: Build Jekyll site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: ./.github/actions/jekyll-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: main-build
          target_path: public
          post_build_commands: |
            cp "${GITHUB_WORKSPACE}/firebase.json" public/
            ls -l
            #ls -l public/
#     - run: |
#         ls -l /github/
#         BUILD_DIR="/github/jekyll_build"
#         ls ${BUILD_DIR}
#         echo ${GITHUB_WORKSPACE}
#         echo ${BUILD_DIR}
#         ls -l ${GITHUB_WORKSPACE}
#         ls -l ${BUILD_DIR}
#         cd ${BUILD_DIR}
#         ls -l
#         pwd

