name: Builds and deploys Jekyll site

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: ./.github/actions/jekyll-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: dev-build
          target_path: public
          post_build_commands: |
            cp "${GITHUB_WORKSPACE}/firebase.json" .
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev-build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_EPOCH_WEBSITE_DEV }}'
          channelId: live
          projectId: epoch-website-dev
