name: Updates the databases in the development branch (currently, just the ML inputs one)

on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: dev
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: python utils/update-databases.py
      - name: Commit and push
        run: |
          git config user.name "${{github.actor}}"
          git config user.email "${{github.actor}}@users.noreply.github.com"

          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit. Done."
            exit 0
          fi

          git add -A
          git commit -m "database update"
          git push
